# Generated by Django 5.0.6 on 2024-05-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0002_requestedgmc'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedgmc',
            name='or_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestedgmc',
            name='reason',
            field=models.TextField(),
        ),
    ]
