# Generated by Django 5.0.6 on 2024-05-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0003_requestedgmc_or_num_alter_requestedgmc_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedgmc',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
